export const responses = {
    "hello": "Hello! How can I assist you today?",
    "weather": "The current weather is sunny with a temperature of 25°C.",
    "greetings": "Greetings! What can I do for you?",
    "time": "The current time is 2:30 PM.",
    "joke": "Why don't scientists trust atoms? Because they make up everything!",
    "help": "I'm here to help. What do you need assistance with?",
    "goodbye": "Goodbye! If you have more questions, feel free to ask.",
    "thanks": "You're welcome! If you need anything else, just let me know.",
    "music": "Discover the latest hits on your favorite music platform.",
    "news": "Explore the latest headlines in technology, sports, and world events.",
    "movie": "Recommendations for your movie night cravings.",
    "food": "Explore new recipes or order from your favorite restaurant.",
    "sports": "Stay updated on your favorite sports and scores.",
    "programming": "Coding challenges and assistance for your projects.",
    "travel": "Dreamy destinations based on your preferences.",
    "technology": "Explore the vast world of technology.",
    "math": "Assistance with any math problems you encounter.",
    "history": "Fascinating facts and stories from different eras.",
    "books": "Book recommendations across various genres.",
    "health": "Guidance on health-related questions or topics.",
    "education": "Key insights into learning and studying.",
    "science": "Explore the fascinating world of science.",
    "trends": "Stay updated on the latest trends.",
    "games": "Discover popular games and gaming-related topics.",
    "motivation": "Boost your spirits with motivational tips.",
    "workout": "Fitness routines and advice for a healthy lifestyle.",
    
    "languages": "Language learning advice and practice.",
    
    "quotes": "Inspirational quotes on various topics.",
    "trivia": "Enjoy a session of interesting trivia.",
    "mindfulness": "Tips and exercises for mindfulness.",
    "humor": "A dose of humor to brighten your day.",
    "code": "Valuable insights and assistance with coding.",
    "style": "Fashion advice and tips for self-expression.",
    "recipes": "Delicious recipes for your culinary adventures.",
    "innovations": "Explore constant tech innovations.",
    "anime": "Must-watch anime series recommendations.",
    "cosmos": "Explore the vastness of the cosmos and astronomy.",
    "environment": "Tips and topics on eco-friendly living.",
    "podcasts": "Discover and recommend interesting podcasts.",
    "celebs": "Stay updated on the world of celebrities.",
    "selfcare": "Tips for prioritizing self-care.",
    "fitness": "Assistance with your fitness goals.",
    "practice": "Guidance on mindfulness practices.",
    "projects": "Assistance and ideas for coding projects.",
    "photography": "Tips and topics on capturing moments.",
    "nature": "Explore the beauty of nature.",
    "socialmedia": "Stay updated on social media strategies and trends.",
    "cooking": "Culinary advice and delicious recipes.",
    
    "discussions": "Engage in discussions on evolving technology.",
    "career": "Insights and advice for navigating your career.",
    "hobbies": "Explore new and exciting hobbies.",
    "challenges": "Fun and challenging coding problems.",
    "films": "Recommendations for your film preferences.",
    "learner": "Embark on a journey as a lifelong learner.",
    "destinations": "Travel recommendations and tips.",
    "exploration": "Explore diverse scientific topics.",
    "language": "Tips and resources for learning new languages.",
    "discovery": "Discover new music genres and artists.",
    "expression": "Explore various forms of artistic expression.",
    "literature": "Recommendations and discussions on literature.",
    "advice": "Health advice and answers to your questions.",
    "programming_help": "Assistance with coding challenges and concepts.",
    "tech_talk": "Engage in discussions on evolving technology.",
    "game_recommendations": "Recommendations for your gaming preferences.",
    "motivational_quotes": "Inspiring quotes to keep you motivated.",
    "fitness_guidance": "Guidance on achieving your fitness goals.",
    "pets": "Share stories or get tips on pet care.",
    "language_learning": "Advice and practice for language learning.",
    "art": "Explore various forms of artistic expression.",
    "space": "The cosmos is vast and mysterious. Interested in space exploration or astronomy?",
    
    "celebrities": "Interested in the world of celebrities? I can share the latest gossip or news.",
    "culture": "Explore diverse cultural topics and traditions.",
    "meditation": "Practice meditation for a calm and centered mind.",
    "finance": "Get financial tips and insights for better money management.",
    "fashion": "Stay trendy with the latest in the world of fashion.",
    "podcast": "Discover and recommend interesting podcasts.",
    "mindset": "Cultivate a positive and growth-oriented mindset.",
    "coding": "Unlock coding challenges and enhance your programming skills.",
    "decor": "Spruce up your space with stylish decorating ideas.",
    "traveling": "Plan your next adventure with travel recommendations.",
    
    "painting": "Express yourself through the art of painting.",
    "gardening": "Discover the joys of gardening and plant care.",
    "film": "Explore film recommendations and cinematic discussions.",
    "writing": "Hone your writing skills with creative writing tips.",
    "wellness": "Prioritize overall wellness for a balanced lifestyle.",
    "gaming": "Dive into the world of gaming with recommendations and updates.",
   
    "codingtips": "Receive practical coding tips and tricks for efficiency.",
    "codingcommunity": "Connect with a coding community for collaborative learning.",
    "hiking": "Embark on scenic hikes with nature-loving enthusiasts.",
    "phototips": "Capture stunning moments with photography tips.",
    "reading": "Explore book recommendations and literary discussions.",
    "motivational": "Fuel your motivation with inspirational quotes.",
    "technologynews": "Stay informed with the latest in technology news.",
    "yoga": "Explore the benefits of yoga for physical and mental well-being.",
    "astronomy": "Discover the wonders of the universe with astronomy.",
    "ecofriendly": "Adopt eco-friendly practices for a sustainable lifestyle.",
    "healthyliving": "Embrace a healthy lifestyle with wellness tips.",
    "nutrition": "Learn about proper nutrition for a balanced diet.",
    "parenting": "Navigate the journey of parenting with helpful tips.",
    "codingjourney": "Embark on a coding journey with learning resources.",
    "startup": "Explore the world of startups and entrepreneurship.",
    "careeradvice": "Receive valuable advice for advancing in your career.",
    "DIY": "Get creative with Do-It-Yourself (DIY) projects.",
    "creativity": "Nurture your creativity with artistic expression.",
    "architecture": "Explore architectural marvels and design concepts.",
    "cuisine": "Delve into diverse cuisines with culinary exploration.",
    "crafting": "Express yourself through various crafting projects.",
    "entrepreneurship": "Explore the world of entrepreneurship and startups.",
   
    "traveltips": "Plan your travels with helpful travel tips.",
   
    "coding101": "Get started with coding basics and foundational concepts.",
    
}
